# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('GT', 'Greater Than'), ('GTE', 'Greater Than or Equal'), ('LT', 'Less Than'), ('LTE', 'Less Than or Equal'), ('EQ', 'Equal'), ('NEQ', 'Not Equal')], max_length=20)),
                ('threshold_float', models.FloatField(blank=True, null=True)),
                ('threshold_integer', models.BigIntegerField(blank=True, null=True)),
                ('threshold_boolean', models.BooleanField(blank=True, null=True)),
                ('threshold_text', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('message_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('SUPPRESSED', 'Suppressed')], db_index=True, default='OPEN', max_length=30)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='datacenters.datacenter')),
            ],
            options={
                'db_table': 'alert_events',
            },
        ),
    ]
