# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('datacenters', '0001_initial'),
        ('devices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='telemetry.metricdefinition'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='datacenters.datacenter'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='telemetry.metricdefinition'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='alert_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='alerts.alertrule'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'data_center'], name='alert_rules_organiz_3351ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['device_type'], name='alert_rules_device__09bde6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['device'], name='alert_rules_device__80ded8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric'], name='alert_rules_metric__a84010_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['severity'], name='alert_rules_severit_b37e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_active'], name='alert_rules_is_acti_699c44_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['organization', 'data_center'], name='alert_event_organiz_dc5879_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['device', 'status'], name='alert_event_device__82dc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['severity', 'status'], name='alert_event_severit_d02282_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['triggered_at'], name='alert_event_trigger_03b735_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status'], name='alert_event_status_9da388_idx'),
        ),
    ]
