# Generated by Codex on 2026-07-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_initial"),
        ("access_control", "0003_userresourceaccess_refactor"),
        ("organizations", "0001_initial"),
        ("datacenters", "0001_initial"),
        ("devices", "0001_initial"),
        ("telemetry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertevent",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="resolved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_alerts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="resolution_type",
            field=models.CharField(blank=True, choices=[("AUTO", "Auto"), ("MANUAL", "Manual"), ("SUPPRESSED", "Suppressed"), ("EXPIRED", "Expired")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="acknowledge_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="resolve_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="occurrence_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AlertConditionState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_seen_at", models.DateTimeField(db_index=True)),
                ("last_seen_at", models.DateTimeField(db_index=True)),
                ("last_value_float", models.FloatField(blank=True, null=True)),
                ("last_value_integer", models.BigIntegerField(blank=True, null=True)),
                ("last_value_boolean", models.BooleanField(blank=True, null=True)),
                ("last_value_text", models.TextField(blank=True, null=True)),
                ("condition_is_active", models.BooleanField(db_index=True, default=True)),
                ("alert_rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="condition_states", to="alerts.alertrule")),
                ("data_center", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_condition_states", to="datacenters.datacenter")),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_condition_states", to="devices.device")),
                ("metric", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="alert_condition_states", to="telemetry.metricdefinition")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_condition_states", to="organizations.organization")),
            ],
            options={
                "db_table": "alert_condition_states",
            },
        ),
        migrations.CreateModel(
            name="AlertEventLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("OPENED", "Opened"), ("UPDATED", "Updated"), ("ACKNOWLEDGED", "Acknowledged"), ("RESOLVED", "Resolved"), ("SUPPRESSED", "Suppressed"), ("ESCALATED", "Escalated"), ("COMMENTED", "Commented"), ("NOTIFICATION_CREATED", "Notification Created"), ("NOTIFICATION_SENT", "Notification Sent"), ("NOTIFICATION_FAILED", "Notification Failed")], db_index=True, max_length=50)),
                ("old_status", models.CharField(blank=True, max_length=30, null=True)),
                ("new_status", models.CharField(blank=True, max_length=30, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("value_snapshot", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alert_event_logs", to=settings.AUTH_USER_MODEL)),
                ("alert_event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="alerts.alertevent")),
            ],
            options={
                "db_table": "alert_event_logs",
            },
        ),
        migrations.CreateModel(
            name="AlertComment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                ("alert_event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="alerts.alertevent")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alert_comments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "alert_comments",
            },
        ),
        migrations.CreateModel(
            name="AlertEscalationPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("severity", models.CharField(choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical"), ("EMERGENCY", "Emergency")], max_length=20)),
                ("if_not_acknowledged_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("if_not_resolved_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("channel", models.CharField(choices=[("WEB", "Web"), ("EMAIL", "Email"), ("SMS", "SMS"), ("WEBHOOK", "Webhook")], default="WEB", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("data_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_escalation_policies", to="datacenters.datacenter")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_escalation_policies", to="organizations.organization")),
                ("target_role", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alert_escalation_policies", to="access_control.role")),
            ],
            options={
                "db_table": "alert_escalation_policies",
            },
        ),
        migrations.CreateModel(
            name="AlertSuppressionWindow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_alert_suppression_windows", to=settings.AUTH_USER_MODEL)),
                ("data_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_suppression_windows", to="datacenters.datacenter")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_suppression_windows", to="devices.device")),
                ("metric", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_suppression_windows", to="telemetry.metricdefinition")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_suppression_windows", to="organizations.organization")),
            ],
            options={
                "db_table": "alert_suppression_windows",
            },
        ),
        migrations.AddField(
            model_name="alertescalationpolicy",
            name="target_users",
            field=models.ManyToManyField(blank=True, related_name="alert_escalation_policies", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["last_seen_at"], name="ae_lastseen_idx"),
        ),
        migrations.AddConstraint(
            model_name="alertconditionstate",
            constraint=models.UniqueConstraint(fields=("organization", "data_center", "device", "metric", "alert_rule"), name="uq_alert_condition_state"),
        ),
        migrations.AddIndex(
            model_name="alertconditionstate",
            index=models.Index(fields=["organization", "data_center"], name="acs_org_dc_idx"),
        ),
        migrations.AddIndex(
            model_name="alertconditionstate",
            index=models.Index(fields=["device", "metric"], name="acs_dev_metric_idx"),
        ),
        migrations.AddIndex(
            model_name="alertconditionstate",
            index=models.Index(fields=["alert_rule"], name="acs_rule_idx"),
        ),
        migrations.AddIndex(
            model_name="alertconditionstate",
            index=models.Index(fields=["condition_is_active"], name="acs_active_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteventlog",
            index=models.Index(fields=["alert_event", "action"], name="ael_event_action_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteventlog",
            index=models.Index(fields=["created_at"], name="ael_created_idx"),
        ),
        migrations.AddIndex(
            model_name="alertcomment",
            index=models.Index(fields=["alert_event"], name="ac_event_idx"),
        ),
        migrations.AddIndex(
            model_name="alertcomment",
            index=models.Index(fields=["user"], name="ac_user_idx"),
        ),
        migrations.AddIndex(
            model_name="alertcomment",
            index=models.Index(fields=["created_at"], name="ac_created_idx"),
        ),
        migrations.AddIndex(
            model_name="alertescalationpolicy",
            index=models.Index(fields=["organization", "data_center"], name="aep_org_dc_idx"),
        ),
        migrations.AddIndex(
            model_name="alertescalationpolicy",
            index=models.Index(fields=["severity"], name="aep_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="alertescalationpolicy",
            index=models.Index(fields=["is_active"], name="aep_active_idx"),
        ),
        migrations.AddIndex(
            model_name="alertsuppressionwindow",
            index=models.Index(fields=["organization", "data_center"], name="asw_org_dc_idx"),
        ),
        migrations.AddIndex(
            model_name="alertsuppressionwindow",
            index=models.Index(fields=["device"], name="asw_dev_idx"),
        ),
        migrations.AddIndex(
            model_name="alertsuppressionwindow",
            index=models.Index(fields=["metric"], name="asw_metric_idx"),
        ),
        migrations.AddIndex(
            model_name="alertsuppressionwindow",
            index=models.Index(fields=["starts_at", "ends_at"], name="asw_window_idx"),
        ),
        migrations.AddIndex(
            model_name="alertsuppressionwindow",
            index=models.Index(fields=["is_active"], name="asw_active_idx"),
        ),
    ]
