# Generated by Django 5.0.6 on 2026-07-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_engine_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertcomment',
            new_name='alert_comme_alert_e_3be377_idx',
            old_name='ac_event_idx',
        ),
        migrations.RenameIndex(
            model_name='alertcomment',
            new_name='alert_comme_user_id_599c4e_idx',
            old_name='ac_user_idx',
        ),
        migrations.RenameIndex(
            model_name='alertcomment',
            new_name='alert_comme_created_357120_idx',
            old_name='ac_created_idx',
        ),
        migrations.RenameIndex(
            model_name='alertconditionstate',
            new_name='alert_condi_organiz_a068b0_idx',
            old_name='acs_org_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='alertconditionstate',
            new_name='alert_condi_device__97f460_idx',
            old_name='acs_dev_metric_idx',
        ),
        migrations.RenameIndex(
            model_name='alertconditionstate',
            new_name='alert_condi_alert_r_e527d0_idx',
            old_name='acs_rule_idx',
        ),
        migrations.RenameIndex(
            model_name='alertconditionstate',
            new_name='alert_condi_conditi_9090bc_idx',
            old_name='acs_active_idx',
        ),
        migrations.RenameIndex(
            model_name='alertescalationpolicy',
            new_name='alert_escal_organiz_766dbb_idx',
            old_name='aep_org_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='alertescalationpolicy',
            new_name='alert_escal_severit_642d1c_idx',
            old_name='aep_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='alertescalationpolicy',
            new_name='alert_escal_is_acti_94f5e7_idx',
            old_name='aep_active_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='alert_event_last_se_2c007f_idx',
            old_name='ae_lastseen_idx',
        ),
        migrations.RenameIndex(
            model_name='alerteventlog',
            new_name='alert_event_alert_e_644f27_idx',
            old_name='ael_event_action_idx',
        ),
        migrations.RenameIndex(
            model_name='alerteventlog',
            new_name='alert_event_created_bd09c3_idx',
            old_name='ael_created_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionwindow',
            new_name='alert_suppr_organiz_e8488c_idx',
            old_name='asw_org_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionwindow',
            new_name='alert_suppr_device__ebc525_idx',
            old_name='asw_dev_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionwindow',
            new_name='alert_suppr_metric__c641b7_idx',
            old_name='asw_metric_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionwindow',
            new_name='alert_suppr_starts__44ac31_idx',
            old_name='asw_window_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionwindow',
            new_name='alert_suppr_is_acti_4f215e_idx',
            old_name='asw_active_idx',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('EMERGENCY', 'Emergency')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('EMERGENCY', 'Emergency')], default='WARNING', max_length=20),
        ),
    ]
