from __future__ import annotations

from .enums import ReportDefinitionCategory


REPORT_DEFINITION_SEEDS = [
    {
        "code": "DEVICE_INVENTORY",
        "name": "Device Inventory",
        "description": "Exports the current inventory of devices, models, rooms, racks, and locations.",
        "category": ReportDefinitionCategory.INVENTORY,
        "generator_key": "device_inventory",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "data_center_id": {"type": ["string", "null"]},
                "room_id": {"type": ["string", "null"]},
                "rack_id": {"type": ["string", "null"]},
                "device_id": {"type": ["string", "null"]},
                "device_model_id": {"type": ["string", "null"]},
                "device_type_id": {"type": ["string", "null"]},
                "status": {"type": ["string", "null"]},
                "is_active": {"type": ["boolean", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": False,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "TELEMETRY_EXPORT",
        "name": "Telemetry Export",
        "description": "Exports historical telemetry points for selected devices or locations.",
        "category": ReportDefinitionCategory.TELEMETRY,
        "generator_key": "telemetry_export",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "metric_codes": {"type": "array", "items": {"type": "string"}},
                "default_columns": {"type": "array", "items": {"type": "string"}},
                "aggregation": {"type": ["string", "null"]},
                "quality_filter": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": True,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "ALERT_SUMMARY",
        "name": "Daily alert summary",
        "description": "Summarises alerts by severity, status, and common operational filters for day-by-day review.",
        "category": ReportDefinitionCategory.ALERT,
        "generator_key": "alert_summary",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "severity": {"type": ["string", "null"]},
                "status": {"type": ["string", "null"]},
                "data_center_id": {"type": ["string", "null"]},
                "device_id": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": False,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "ALERT_DETAIL",
        "name": "Alert Detail",
        "description": "Exports detailed alert events with acknowledgement and resolution information.",
        "category": ReportDefinitionCategory.ALERT,
        "generator_key": "alert_export",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "severity": {"type": ["string", "null"]},
                "status": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": False,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "NOTIFICATION_DELIVERY",
        "name": "Notification Delivery",
        "description": "Exports notification delivery history by channel, recipient, and status.",
        "category": ReportDefinitionCategory.NOTIFICATION,
        "generator_key": "notification_delivery",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "channel": {"type": ["string", "null"]},
                "status": {"type": ["string", "null"]},
                "recipient_id": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": False,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "AUDIT_EXPORT",
        "name": "Audit Export",
        "description": "Exports audit log events with actor, resource, and activity details.",
        "category": ReportDefinitionCategory.AUDIT,
        "generator_key": "audit_export",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "actions": {"type": "array", "items": {"type": "string"}},
                "resource_type": {"type": ["string", "null"]},
                "resource_id": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL"],
        "requires_telemetry": False,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "ENVIRONMENTAL_TREND",
        "name": "Environmental Trend",
        "description": "Exports room environment telemetry such as temperature and humidity.",
        "category": ReportDefinitionCategory.ENVIRONMENT,
        "generator_key": "room_environment",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "metrics": {"type": "array", "items": {"type": "string"}},
                "aggregation": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": True,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
    {
        "code": "UPS_PERFORMANCE",
        "name": "UPS Performance",
        "description": "Exports historical UPS telemetry such as load, voltage, current, battery status, and runtime.",
        "category": ReportDefinitionCategory.POWER,
        "generator_key": "ups_performance",
        "parameter_schema": {
            "type": "object",
            "properties": {
                "date_from": {"type": ["string", "null"]},
                "date_to": {"type": ["string", "null"]},
                "metric_codes": {"type": "array", "items": {"type": "string"}},
                "device_id": {"type": ["string", "null"]},
                "data_center_id": {"type": ["string", "null"]},
            },
        },
        "supported_formats": ["CSV", "XLSX", "PDF"],
        "supported_delivery_channels": ["EMAIL", "SMS"],
        "requires_telemetry": True,
        "requires_data_center": False,
        "is_system": True,
        "is_active": True,
        "version": 1,
    },
]
