from __future__ import annotations

REPORT_TEMPLATE_SEEDS = [
    {
        "name": "Alert Summary",
        "code": "ALERT_SUMMARY",
        "description": "Summary of alert activity, severity breakdown, and resolution counts.",
        "config": {
            "report_type": "alert_summary",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": [],
            "optional_filters": [
                "date_from",
                "date_to",
                "data_center_id",
                "device_id",
                "device_model_id",
                "device_type_id",
                "room_id",
                "rack_id",
                "metric_codes",
                "severity",
                "status",
            ],
            "default_columns": ["section", "label", "value"],
            "max_date_range_days": 90,
        },
    },
    {
        "name": "Notification Delivery",
        "code": "NOTIFICATION_DELIVERY",
        "description": "Notification delivery status grouped by channel and lifecycle state.",
        "config": {
            "report_type": "notification_delivery",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": [],
            "optional_filters": [
                "date_from",
                "date_to",
                "recipient_id",
                "channel",
                "status",
                "alert_id",
                "device_id",
            ],
            "default_columns": ["section", "label", "value"],
            "max_date_range_days": 90,
        },
    },
    {
        "name": "Device Inventory",
        "code": "DEVICE_INVENTORY",
        "description": "Active device inventory scoped to the organization and data center.",
        "config": {
            "report_type": "device_inventory",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": [],
            "optional_filters": [
                "data_center_id",
                "room_id",
                "rack_id",
                "device_id",
                "device_model_id",
                "device_type_id",
                "status",
                "is_active",
            ],
            "default_columns": [
                "organization",
                "data_center",
                "room",
                "rack",
                "device",
                "code",
                "hostname",
                "ip_address",
                "device_type",
                "device_model",
                "vendor",
                "status",
                "is_active",
                "last_seen",
            ],
        },
    },
    {
        "name": "Alert Export",
        "code": "ALERT_EXPORT",
        "description": "Exports detailed alert history with device, metric, severity, status, acknowledgement, and resolution details.",
        "config": {
            "report_type": "alert_export",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": ["date_from", "date_to"],
            "optional_filters": [
                "device_id",
                "device_model_id",
                "device_type_id",
                "data_center_id",
                "room_id",
                "rack_id",
                "metric_codes",
                "severity",
                "status",
                "source",
            ],
            "default_columns": [
                "triggered_at",
                "resolved_at",
                "organization",
                "data_center",
                "room",
                "rack",
                "device",
                "device_model",
                "metric",
                "severity",
                "status",
                "message",
                "occurrence_count",
                "acknowledged_by",
                "resolved_by",
            ],
            "max_date_range_days": 90,
        },
    },
    {
        "name": "Audit Export",
        "code": "AUDIT_EXPORT",
        "description": "Exports audit log records for user actions, system actions, resources, and IP activity.",
        "config": {
            "report_type": "audit_export",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": ["date_from", "date_to"],
            "optional_filters": ["actor_id", "actions", "resource_type", "resource_id", "ip_address"],
            "default_columns": [
                "created_at",
                "actor",
                "action",
                "resource_type",
                "resource_id",
                "organization",
                "message",
                "ip_address",
                "user_agent",
            ],
            "max_date_range_days": 90,
        },
    },
    {
        "name": "Telemetry Export",
        "code": "TELEMETRY_EXPORT",
        "description": "Exports selected historical telemetry metrics for devices, models, rooms, racks, or data centers.",
        "config": {
            "report_type": "telemetry_export",
            "output_format": "csv",
            "allowed_output_formats": ["csv"],
            "required_filters": ["date_from", "date_to", "metric_codes"],
            "optional_filters": [
                "device_id",
                "device_model_id",
                "device_type_id",
                "data_center_id",
                "room_id",
                "rack_id",
            ],
            "default_columns": [
                "timestamp",
                "organization",
                "data_center",
                "room",
                "rack",
                "device",
                "device_model",
                "device_type",
                "metric_code",
                "metric_name",
                "value",
                "unit",
                "quality",
            ],
            "max_date_range_days": 31,
        },
    },
]
