# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenters', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_models',
            },
        ),
        migrations.CreateModel(
            name='PollingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('SNMP', 'SNMP'), ('MODBUS_TCP', 'Modbus TCP'), ('MODBUS_RTU_GATEWAY', 'Modbus RTU Gateway'), ('MQTT', 'MQTT'), ('HTTP_API', 'HTTP API'), ('PING', 'Ping'), ('MANUAL', 'Manual')], max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('stale_after_seconds', models.PositiveIntegerField(default=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'polling_profiles',
            },
        ),
        migrations.CreateModel(
            name='SNMPOIDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oid', models.CharField(max_length=255)),
                ('data_type', models.CharField(default='float', max_length=50)),
                ('scale_factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('offset_value', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'snmp_oid_mappings',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('MAINTENANCE', 'Maintenance'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='datacenters.datacenter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='datacenters.rack')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='datacenters.room')),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicemodel')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('SNMP', 'SNMP'), ('MODBUS_TCP', 'Modbus TCP'), ('MODBUS_RTU_GATEWAY', 'Modbus RTU Gateway'), ('MQTT', 'MQTT'), ('HTTP_API', 'HTTP API'), ('PING', 'Ping'), ('MANUAL', 'Manual')], max_length=50)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password_encrypted', models.TextField(blank=True, null=True)),
                ('snmp_version', models.CharField(blank=True, choices=[('V1', 'v1'), ('V2C', 'v2c'), ('V3', 'v3')], max_length=10, null=True)),
                ('snmp_community_encrypted', models.TextField(blank=True, null=True)),
                ('snmp_v3_auth_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_v3_auth_key_encrypted', models.TextField(blank=True, null=True)),
                ('snmp_v3_priv_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_v3_priv_key_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='devices.device')),
            ],
            options={
                'db_table': 'device_credentials',
            },
        ),
        migrations.CreateModel(
            name='DevicePollingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polling_config', to='devices.device')),
            ],
            options={
                'db_table': 'device_polling_configs',
            },
        ),
        migrations.CreateModel(
            name='DeviceProtocolConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('SNMP', 'SNMP'), ('MODBUS_TCP', 'Modbus TCP'), ('MODBUS_RTU_GATEWAY', 'Modbus RTU Gateway'), ('MQTT', 'MQTT'), ('HTTP_API', 'HTTP API'), ('PING', 'Ping'), ('MANUAL', 'Manual')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_configs', to='devices.device')),
            ],
            options={
                'db_table': 'device_protocol_configs',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('POWER', 'Power'), ('COOLING', 'Cooling'), ('ENVIRONMENT', 'Environment'), ('NETWORK', 'Network'), ('SECURITY', 'Security'), ('GENERATOR', 'Generator'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_types',
                'indexes': [models.Index(fields=['category'], name='device_type_categor_50e1b6_idx'), models.Index(fields=['code'], name='device_type_code_6992be_idx')],
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype'),
        ),
        migrations.CreateModel(
            name='ModbusRegisterMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slave_id', models.PositiveIntegerField(default=1)),
                ('function_code', models.PositiveSmallIntegerField(choices=[(1, 'Read Coils'), (2, 'Read Discrete Inputs'), (3, 'Read Holding Registers'), (4, 'Read Input Registers')], default=3)),
                ('register_address', models.PositiveIntegerField()),
                ('register_count', models.PositiveIntegerField(default=1)),
                ('data_type', models.CharField(max_length=50)),
                ('byte_order', models.CharField(default='BIG', max_length=20)),
                ('word_order', models.CharField(default='BIG', max_length=20)),
                ('scale_factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('offset_value', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modbus_register_mappings', to='devices.devicemodel')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modbus_register_mappings', to='devices.devicetype')),
            ],
            options={
                'db_table': 'modbus_register_mappings',
            },
        ),
    ]
