# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusregistermapping',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modbus_register_mappings', to='telemetry.metricdefinition'),
        ),
        migrations.AddIndex(
            model_name='pollingprofile',
            index=models.Index(fields=['protocol'], name='polling_pro_protoco_6b9c90_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingprofile',
            index=models.Index(fields=['priority'], name='polling_pro_priorit_90437a_idx'),
        ),
        migrations.AddIndex(
            model_name='pollingprofile',
            index=models.Index(fields=['is_active'], name='polling_pro_is_acti_88d077_idx'),
        ),
        migrations.AddField(
            model_name='devicepollingconfig',
            name='polling_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_configs', to='devices.pollingprofile'),
        ),
        migrations.AddField(
            model_name='snmpoidmapping',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_oid_mappings', to='devices.devicemodel'),
        ),
        migrations.AddField(
            model_name='snmpoidmapping',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_oid_mappings', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='snmpoidmapping',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_oid_mappings', to='telemetry.metricdefinition'),
        ),
        migrations.AddField(
            model_name='snmpoidmapping',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_oid_mappings', to='devices.vendor'),
        ),
        migrations.AddField(
            model_name='modbusregistermapping',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modbus_register_mappings', to='devices.vendor'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='devices.vendor'),
        ),
        migrations.AddIndex(
            model_name='devicecredential',
            index=models.Index(fields=['device', 'protocol'], name='device_cred_device__69e8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecredential',
            index=models.Index(fields=['is_active'], name='device_cred_is_acti_b9ff9a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceprotocolconfig',
            index=models.Index(fields=['device', 'protocol'], name='device_prot_device__50d1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceprotocolconfig',
            index=models.Index(fields=['is_enabled'], name='device_prot_is_enab_4402e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceprotocolconfig',
            constraint=models.UniqueConstraint(fields=('device', 'protocol', 'host', 'port'), name='uq_device_protocol_endpoint'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'data_center'], name='devices_organiz_571d48_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['data_center', 'device_type'], name='devices_data_ce_5928d8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='devices_ip_addr_e9105f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_status_9f14cf_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen_at'], name='devices_last_se_ab9139_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='devices_is_acti_9ea4e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('data_center', 'code'), name='uq_dc_device_code'),
        ),
        migrations.AddIndex(
            model_name='devicepollingconfig',
            index=models.Index(fields=['is_enabled'], name='device_poll_is_enab_ac197d_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepollingconfig',
            index=models.Index(fields=['next_poll_at'], name='device_poll_next_po_bc9070_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepollingconfig',
            index=models.Index(fields=['last_polled_at'], name='device_poll_last_po_3fecf2_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpoidmapping',
            index=models.Index(fields=['device_type'], name='snmp_oid_ma_device__65d0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpoidmapping',
            index=models.Index(fields=['vendor'], name='snmp_oid_ma_vendor__aa251d_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpoidmapping',
            index=models.Index(fields=['device_model'], name='snmp_oid_ma_device__4b4c52_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpoidmapping',
            index=models.Index(fields=['oid'], name='snmp_oid_ma_oid_18bef8_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpoidmapping',
            index=models.Index(fields=['is_active'], name='snmp_oid_ma_is_acti_9e6d57_idx'),
        ),
        migrations.AddIndex(
            model_name='modbusregistermapping',
            index=models.Index(fields=['device_type'], name='modbus_regi_device__97a623_idx'),
        ),
        migrations.AddIndex(
            model_name='modbusregistermapping',
            index=models.Index(fields=['vendor'], name='modbus_regi_vendor__1771ea_idx'),
        ),
        migrations.AddIndex(
            model_name='modbusregistermapping',
            index=models.Index(fields=['device_model'], name='modbus_regi_device__9fb5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='modbusregistermapping',
            index=models.Index(fields=['register_address'], name='modbus_regi_registe_fe4232_idx'),
        ),
        migrations.AddIndex(
            model_name='modbusregistermapping',
            index=models.Index(fields=['is_active'], name='modbus_regi_is_acti_c9f0f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_number'), name='uq_vendor_model_number'),
        ),
    ]
