# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_widgets', to='devices.device'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_widgets', to='telemetry.metricdefinition'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization', 'data_center'], name='dashboards_organiz_845935_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_active'], name='dashboards_is_acti_bdbff2_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_org_dashboard_code'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard'], name='dashboard_w_dashboa_76f849_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['device'], name='dashboard_w_device__c4958b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['metric'], name='dashboard_w_metric__904c3c_idx'),
        ),
    ]
