# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_centers', to='organizations.organization')),
            ],
            options={
                'db_table': 'data_centers',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('SERVER_ROOM', 'Server Room'), ('POWER_ROOM', 'Power Room'), ('NETWORK_ROOM', 'Network Room'), ('CONTROL_ROOM', 'Control Room'), ('OTHER', 'Other')], default='SERVER_ROOM', max_length=50)),
                ('floor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='datacenters.datacenter')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='datacenters.datacenter')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='datacenters.room')),
            ],
            options={
                'db_table': 'rows',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('rack_u_height', models.PositiveIntegerField(default=42)),
                ('power_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position_in_row', models.PositiveIntegerField(blank=True, null=True)),
                ('row_label', models.CharField(blank=True, max_length=50, null=True)),
                ('position_label', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='datacenters.datacenter')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='datacenters.room')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='datacenters.row')),
            ],
            options={
                'db_table': 'racks',
            },
        ),
        migrations.AddIndex(
            model_name='datacenter',
            index=models.Index(fields=['organization', 'status'], name='data_center_organiz_038e35_idx'),
        ),
        migrations.AddIndex(
            model_name='datacenter',
            index=models.Index(fields=['code'], name='data_center_code_daea1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='datacenter',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_org_datacenter_code'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['data_center'], name='rooms_data_ce_c23dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='rooms_room_ty_7b8350_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('data_center', 'code'), name='uq_dc_room_code'),
        ),
        migrations.AddIndex(
            model_name='row',
            index=models.Index(fields=['data_center'], name='rows_data_ce_f68e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='row',
            index=models.Index(fields=['room'], name='rows_room_id_cfc70f_idx'),
        ),
        migrations.AddIndex(
            model_name='row',
            index=models.Index(fields=['code'], name='rows_code_7083f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='uq_room_row_code'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['data_center'], name='racks_data_ce_70e004_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['room'], name='racks_room_id_49562e_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['row'], name='racks_row_id_84822e_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['status'], name='racks_status_d0b3af_idx'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('data_center', 'code'), name='uq_dc_rack_code'),
        ),
    ]
