# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenters', '0001_initial'),
        ('devices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPTrapEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('trap_oid', models.CharField(db_index=True, max_length=255)),
                ('event_code', models.CharField(blank=True, max_length=150, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('raw_varbinds', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('data_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_trap_events', to='datacenters.datacenter')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_trap_events', to='devices.device')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snmp_trap_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'snmp_trap_events',
                'indexes': [models.Index(fields=['source_ip'], name='snmp_trap_e_source__02efd3_idx'), models.Index(fields=['trap_oid'], name='snmp_trap_e_trap_oi_4aec83_idx'), models.Index(fields=['device'], name='snmp_trap_e_device__c14306_idx'), models.Index(fields=['received_at'], name='snmp_trap_e_receive_2d2a92_idx'), models.Index(fields=['is_mapped'], name='snmp_trap_e_is_mapp_a7c999_idx'), models.Index(fields=['is_processed'], name='snmp_trap_e_is_proc_209e84_idx')],
            },
        ),
        migrations.CreateModel(
            name='SNMPTrapOIDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trap_oid', models.CharField(db_index=True, max_length=255)),
                ('event_code', models.CharField(max_length=150)),
                ('event_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('message_template', models.TextField(blank=True, null=True)),
                ('create_alert', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_oid_mappings', to='devices.devicemodel')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_oid_mappings', to='devices.devicetype')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_oid_mappings', to='devices.vendor')),
            ],
            options={
                'db_table': 'snmp_trap_oid_mappings',
                'indexes': [models.Index(fields=['device_type'], name='snmp_trap_o_device__3e5e3d_idx'), models.Index(fields=['vendor'], name='snmp_trap_o_vendor__9f065b_idx'), models.Index(fields=['device_model'], name='snmp_trap_o_device__30a4ed_idx'), models.Index(fields=['trap_oid'], name='snmp_trap_o_trap_oi_226dc9_idx'), models.Index(fields=['is_active'], name='snmp_trap_o_is_acti_e5abbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SNMPTrapSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_sources', to='datacenters.datacenter')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_sources', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_trap_sources', to='organizations.organization')),
            ],
            options={
                'db_table': 'snmp_trap_sources',
                'indexes': [models.Index(fields=['organization', 'data_center'], name='snmp_trap_s_organiz_16c46f_idx'), models.Index(fields=['source_ip'], name='snmp_trap_s_source__482a2a_idx'), models.Index(fields=['is_enabled'], name='snmp_trap_s_is_enab_fa5d92_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='snmptrapsource',
            constraint=models.UniqueConstraint(fields=('source_ip', 'data_center'), name='uq_trap_source_ip_dc'),
        ),
    ]
