# Generated by Django 5.0.6 on 2026-07-28 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNMPMIBDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_name", models.CharField(db_index=True, max_length=255)),
                ("symbol", models.CharField(db_index=True, max_length=255)),
                ("oid", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("DEPRECATED", "Deprecated"),
                            ("OBSOLETE", "Obsolete"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("object_names", models.JSONField(blank=True, default=list)),
                ("source_file", models.CharField(blank=True, max_length=500, null=True)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("imported_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "snmp_mib_definitions",
            },
        ),
        migrations.AddConstraint(
            model_name="snmpmibdefinition",
            constraint=models.UniqueConstraint(fields=("module_name", "symbol", "oid"), name="uq_snmp_mib_definition"),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="resolution_source",
            field=models.CharField(
                choices=[
                    ("DATABASE", "Database Mapping"),
                    ("MIB", "MIB Fallback"),
                    ("UNKNOWN", "Unknown"),
                ],
                db_index=True,
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="mib_module",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="mib_symbol",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="mib_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="mib_status",
            field=models.CharField(
                choices=[
                    ("CURRENT", "Current"),
                    ("DEPRECATED", "Deprecated"),
                    ("OBSOLETE", "Obsolete"),
                    ("UNKNOWN", "Unknown"),
                ],
                db_index=True,
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="snmptrapevent",
            name="requires_mapping_review",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
