# Generated by Django 5.0.6 on 2026-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traps', '0002_snmp_mib_definition_and_trap_resolution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmptrapoidmapping',
            name='resolves_event_code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
