# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('datacenters', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatacenterrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdatacenterrole',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='datacenters.datacenter'),
        ),
        migrations.AddField(
            model_name='userdatacenterrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userdatacenterrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='access_control.role'),
        ),
        migrations.AddField(
            model_name='userdatacenterrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_center_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission'),
        ),
        migrations.AddIndex(
            model_name='userdatacenterrole',
            index=models.Index(fields=['user', 'organization'], name='user_data_c_user_id_4e915c_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatacenterrole',
            index=models.Index(fields=['user', 'data_center'], name='user_data_c_user_id_c766e8_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatacenterrole',
            index=models.Index(fields=['role'], name='user_data_c_role_id_5bfca8_idx'),
        ),
        migrations.AddIndex(
            model_name='userdatacenterrole',
            index=models.Index(fields=['is_active'], name='user_data_c_is_acti_316762_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdatacenterrole',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'data_center', 'role'), name='uq_user_org_dc_role'),
        ),
    ]
