# Generated by Django 5.0.6 on 2026-07-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_userresourceaccess_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('ORGANIZATION', 'Organization'), ('DATA_CENTER', 'Data Center'), ('ROOM', 'Room'), ('RACK', 'Rack'), ('DEVICE', 'Device')], default='DATA_CENTER', max_length=50),
        ),
    ]
