# Generated by Django 5.0.6 on 2026-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("ROLE_ASSIGNED", "Role Assigned"),
                    ("ROLE_REMOVED", "Role Removed"),
                    ("ALERT_ACKNOWLEDGED", "Alert Acknowledged"),
                    ("ALERT_RESOLVED", "Alert Resolved"),
                    ("ALERT_SUPPRESSED", "Alert Suppressed"),
                    ("ALERT_ESCALATED", "Alert Escalated"),
                    ("REPORT_GENERATION_REQUESTED", "Report Generation Requested"),
                    ("REPORT_RETRY_REQUESTED", "Report Retry Requested"),
                    ("REPORT_CANCELLED", "Report Cancelled"),
                    ("REPORT_GENERATION_STARTED", "Report Generation Started"),
                    ("REPORT_GENERATED", "Report Generated"),
                    ("REPORT_GENERATION_FAILED", "Report Generation Failed"),
                    ("REPORT_DOWNLOADED", "Report Downloaded"),
                    ("CREDENTIAL_UPDATED", "Credential Updated"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
