# Generated by Django 5.0.6 on 2026-07-30 08:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('reports', '0006_reportschedule_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('RAW_DATA', 'Raw Data'), ('PREVIEW', 'Preview'), ('SUPPORTING', 'Supporting')], default='PRIMARY', max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/artifacts/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=120, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('AVAILABLE', 'Available'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted')], default='GENERATING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_artifacts',
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ALERTS', 'Alerts'), ('NOTIFICATIONS', 'Notifications'), ('INVENTORY', 'Inventory'), ('TELEMETRY', 'Telemetry'), ('AUDIT', 'Audit'), ('ENVIRONMENT', 'Environment')], max_length=50)),
                ('handler_key', models.CharField(max_length=120)),
                ('parameter_schema', models.JSONField(blank=True, default=dict)),
                ('supported_formats', models.JSONField(blank=True, default=list)),
                ('supports_scheduling', models.BooleanField(default=True)),
                ('supports_raw_attachment', models.BooleanField(default=False)),
                ('supports_charts', models.BooleanField(default=False)),
                ('required_permission', models.CharField(blank=True, max_length=120, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'report_definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('recipient_type', models.CharField(choices=[('TO', 'To'), ('CC', 'CC'), ('BCC', 'BCC')], default='TO', max_length=10)),
                ('destination_snapshot', models.CharField(max_length=255)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('ACCEPTED', 'Accepted'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_deliveries',
            },
        ),
        migrations.CreateModel(
            name='ReportScheduleRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('recipient_type', models.CharField(choices=[('TO', 'To'), ('CC', 'CC'), ('BCC', 'BCC')], default='TO', max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'report_schedule_recipients',
            },
        ),
        migrations.RemoveConstraint(
            model_name='reporttemplate',
            name='uq_org_report_template_code',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_organiz_4e6c26_idx',
            old_name='report_sch_org_dc_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_report__a2c5ad_idx',
            old_name='report_sch_type_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_frequen_825450_idx',
            old_name='report_sch_freq_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_is_acti_12ab8c_idx',
            old_name='report_sch_active_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_next_ru_b183af_idx',
            old_name='report_sch_next_run_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='report_sche_created_614495_idx',
            old_name='report_sch_created_idx',
        ),
        migrations.AddField(
            model_name='reportjob',
            name='current_stage',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='definition_code_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='definition_version_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='output_config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='parameters_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_children', to='reports.reportjob'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='queued_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='recipient_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='scope_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='template_config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='template_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='template_version_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='trigger_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('RUN_NOW', 'Run Now'), ('API', 'API'), ('RETRY', 'Retry'), ('SYSTEM', 'System')], default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='attachment_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='consecutive_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='primary_format',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=64),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='branding_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIALLY_SUCCEEDED', 'Partially Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reports.reporttemplate'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(blank=True, choices=[('alert_summary', 'Alert Summary'), ('notification_delivery', 'Notification Delivery'), ('device_inventory', 'Device Inventory'), ('alert_export', 'Alert Export'), ('audit_export', 'Audit Export'), ('telemetry_export', 'Telemetry Export'), ('room_environment', 'Environmental Trends Report')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='reportartifact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.reportjob'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['code'], name='report_defi_code_943931_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['category'], name='report_defi_categor_febb98_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['handler_key'], name='report_defi_handler_f7efc5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_active'], name='report_defi_is_acti_855a87_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['version'], name='report_defi_version_579fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_report_definition_code'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reports.reportdefinition'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='reports.reportdefinition'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='reports.reportdefinition'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['definition'], name='report_jobs_definit_4a3166_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['template'], name='report_jobs_templat_025366_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['schedule'], name='report_jobs_schedul_353f37_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['trigger_source'], name='report_jobs_trigger_1a6831_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['scheduled_for'], name='report_jobs_schedul_6bc74d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['queued_at'], name='report_jobs_queued__0b247c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['definition'], name='report_sche_definit_74e969_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template'], name='report_sche_templat_75e449_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status'], name='report_sche_status_bb62b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['last_run_at'], name='report_sche_last_ru_ddc6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['last_success_at'], name='report_sche_last_su_2e5884_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'code'], name='report_temp_organiz_690a74_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['definition'], name='report_temp_definit_7657be_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='report_temp_is_acti_2cb562_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['version'], name='report_temp_version_a30fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_at'], name='report_temp_created_9dd79c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False), ('scheduled_for__isnull', False)), fields=('schedule', 'scheduled_for'), name='uq_report_job_schedule_scheduled_for'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code', 'version'), name='uq_report_template_org_code_version'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code', 'version'), name='uq_report_template_global_code_version'),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.reportartifact'),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reports.reportjob'),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportschedulerecipient',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_entries', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportschedulerecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedule_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.reportschedulerecipient'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['job', 'artifact_type'], name='report_arti_job_id_01815c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['job', 'status'], name='report_arti_job_id_f8f2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['format'], name='report_arti_format_9fd75a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['created_at'], name='report_arti_created_79ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['schedule', 'channel'], name='report_sche_schedul_818241_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['schedule', 'is_active'], name='report_sche_schedul_310de6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['destination'], name='report_sche_destina_71a655_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['user'], name='report_sche_user_id_134f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportschedulerecipient',
            constraint=models.UniqueConstraint(fields=('schedule', 'channel', 'recipient_type', 'destination'), name='uq_report_schedule_recipient_destination'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['job', 'channel'], name='report_deli_job_id_ac42b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['job', 'status'], name='report_deli_job_id_2c76cc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['schedule', 'channel'], name='report_deli_schedul_a46065_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['recipient', 'attempt_number'], name='report_deli_recipie_2065fe_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['queued_at'], name='report_deli_queued__7c9da4_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdelivery',
            constraint=models.UniqueConstraint(fields=('job', 'recipient', 'channel', 'attempt_number'), name='uq_report_delivery_attempt'),
        ),
    ]
