# Generated by Django 5.0.6 on 2026-08-02 13:32

from django.db import migrations, models


def _rename_index_sql(old_name: str, new_name: str) -> str:
    return f"""
DO $$
BEGIN
    IF to_regclass('public.{old_name}') IS NOT NULL AND to_regclass('public.{new_name}') IS NULL THEN
        EXECUTE 'ALTER INDEX "{old_name}" RENAME TO "{new_name}"';
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reportjob_snapshot_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(_rename_index_sql('report_sch_org_dc_idx', 'report_sche_organiz_4e6c26_idx')),
                migrations.RunSQL(_rename_index_sql('report_sch_type_idx', 'report_sche_report__a2c5ad_idx')),
                migrations.RunSQL(_rename_index_sql('report_sch_freq_idx', 'report_sche_frequen_825450_idx')),
                migrations.RunSQL(_rename_index_sql('report_sch_active_idx', 'report_sche_is_acti_12ab8c_idx')),
                migrations.RunSQL(_rename_index_sql('report_sch_next_run_idx', 'report_sche_next_ru_b183af_idx')),
                migrations.RunSQL(_rename_index_sql('report_sch_created_idx', 'report_sche_created_614495_idx')),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_organiz_4e6c26_idx',
                    old_name='report_sch_org_dc_idx',
                ),
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_report__a2c5ad_idx',
                    old_name='report_sch_type_idx',
                ),
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_frequen_825450_idx',
                    old_name='report_sch_freq_idx',
                ),
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_is_acti_12ab8c_idx',
                    old_name='report_sch_active_idx',
                ),
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_next_ru_b183af_idx',
                    old_name='report_sch_next_run_idx',
                ),
                migrations.RenameIndex(
                    model_name='reportschedule',
                    new_name='report_sche_created_614495_idx',
                    old_name='report_sch_created_idx',
                ),
                migrations.AlterField(
                    model_name='reportschedule',
                    name='report_type',
                    field=models.CharField(choices=[('alert_summary', 'Alert Summary'), ('notification_delivery', 'Notification Delivery'), ('device_inventory', 'Device Inventory'), ('alert_export', 'Alert Export'), ('audit_export', 'Audit Export'), ('telemetry_export', 'Telemetry Export'), ('room_environment', 'Environmental Trends Report')], max_length=100),
                ),
            ],
        ),
    ]
