# Generated by Django 5.0.6 on 2026-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_backfill_reporting_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIALLY_SUCCEEDED', 'Partially Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('QUEUED', 'Pending'), ('RUNNING', 'Processing'), ('SUCCEEDED', 'Completed')], default='QUEUED', max_length=30),
        ),
    ]
