# Generated by Django 5.0.6 on 2026-08-03 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('reports', '0011_report_schedule_compat_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX'), ('PDF', 'PDF')], max_length=30)),
                ('file', models.FileField(upload_to='reports/artifacts/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_artifacts',
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory'), ('TELEMETRY', 'Telemetry'), ('POWER', 'Power'), ('ENVIRONMENT', 'Environment'), ('ALERT', 'Alert'), ('AVAILABILITY', 'Availability'), ('NOTIFICATION', 'Notification'), ('AUDIT', 'Audit'), ('CAPACITY', 'Capacity'), ('COMPLIANCE', 'Compliance'), ('EXECUTIVE', 'Executive'), ('INCIDENT', 'Incident')], max_length=32)),
                ('generator_key', models.CharField(max_length=100, unique=True)),
                ('parameter_schema', models.JSONField(blank=True, default=dict)),
                ('supported_formats', models.JSONField(blank=True, default=list)),
                ('supported_delivery_channels', models.JSONField(blank=True, default=list)),
                ('requires_telemetry', models.BooleanField(default=False)),
                ('requires_data_center', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'report_definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WEB', 'Web'), ('WEBHOOK', 'Webhook')], max_length=30)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('DELIVERING', 'Delivering'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'report_deliveries',
            },
        ),
        migrations.CreateModel(
            name='ReportScheduleRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=30)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'report_schedule_recipients',
            },
        ),
        migrations.RemoveIndex(
            model_name='reportjob',
            name='report_jobs_status_f93e87_idx',
        ),
        migrations.AddField(
            model_name='reportjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='source_event_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='parameter_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=64),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedulerun',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.reportjob'),
        ),
        migrations.AddField(
            model_name='reportschedulerun',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='attachment_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='default_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='include_charts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='include_raw_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='primary_format',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PROCESSING', 'Processing'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='trigger_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('EVENT', 'Event')], default='MANUAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportschedulerun',
            name='trigger_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('EVENT', 'Event')], default='SCHEDULED', max_length=32),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['organization', 'created_at'], name='report_sche_organiz_06b568_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['data_center', 'created_at'], name='report_sche_data_ce_772ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template'], name='report_sche_templat_75e449_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status'], name='report_sche_status_bb62b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerun',
            index=models.Index(fields=['schedule', 'created_at'], name='report_sche_schedul_dbefbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportschedulerun',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_for__isnull', False), ('trigger_source', 'SCHEDULED')), fields=('schedule', 'scheduled_for', 'trigger_source'), name='uq_report_schedule_run_scheduled_window'),
        ),
        migrations.AddField(
            model_name='reportartifact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='reports.reportjob'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['category'], name='report_defi_categor_febb98_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['generator_key'], name='report_defi_generat_4f8660_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_active'], name='report_defi_is_acti_855a87_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['created_at'], name='report_defi_created_a597e3_idx'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reports.reportdefinition'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='reports.reportdefinition'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['organization', 'created_at'], name='report_jobs_organiz_c95604_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['data_center', 'created_at'], name='report_jobs_data_ce_62249a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['definition'], name='report_jobs_definit_4a3166_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['template'], name='report_jobs_templat_025366_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['schedule'], name='report_jobs_schedul_353f37_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['status', 'created_at'], name='report_jobs_status_a52eae_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'created_at'], name='report_temp_organiz_948127_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['definition'], name='report_temp_definit_7657be_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='report_temp_is_acti_2cb562_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), ('requested_by__isnull', False), ('trigger_source', 'MANUAL')), fields=('organization', 'requested_by', 'trigger_source', 'idempotency_key'), name='uq_report_job_manual_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='reportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('definition__isnull', False), ('idempotency_key__isnull', False), ('trigger_source', 'EVENT')), fields=('organization', 'definition', 'trigger_source', 'idempotency_key'), name='uq_report_job_event_definition_idempotency'),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reports.reportjob'),
        ),
        migrations.AddField(
            model_name='reportschedulerecipient',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_recipients', to='reports.reportschedule'),
        ),
        migrations.AddField(
            model_name='reportdelivery',
            name='schedule_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='reports.reportschedulerecipient'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['job'], name='report_arti_job_id_e39755_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['format'], name='report_arti_format_9fd75a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportartifact',
            index=models.Index(fields=['created_at'], name='report_arti_created_79ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['schedule'], name='report_sche_schedul_721149_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['channel'], name='report_sche_channel_5d649a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['is_active'], name='report_sche_is_acti_bd9d90_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedulerecipient',
            index=models.Index(fields=['created_at'], name='report_sche_created_8d51a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportschedulerecipient',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('channel', 'EMAIL'), ('email_address__isnull', False), models.Q(('email_address', ''), _negated=True)), models.Q(('channel', 'SMS'), ('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), _connector='OR'), name='report_schedule_recipient_channel_contact_check'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['job'], name='report_deli_job_id_e63ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['channel'], name='report_deli_channel_f2e951_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['status'], name='report_deli_status_d90beb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['status', 'created_at'], name='report_deli_status_a369bf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['created_at'], name='report_deli_created_0aa69e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['sent_at'], name='report_deli_sent_at_82f19a_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdelivery',
            constraint=models.UniqueConstraint(fields=('job', 'channel', 'recipient'), name='uq_report_delivery_job_channel_recipient'),
        ),
    ]
