# Generated by Django 5.0.6 on 2026-08-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_reportschedule_output_format_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportartifact',
            constraint=models.UniqueConstraint(fields=('job', 'format'), name='uq_report_artifact_job_format'),
        ),
    ]
