# Generated by Django 5.0.6 on 2026-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_reportartifact_uq_report_artifact_job_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportartifact',
            name='file',
            field=models.FileField(max_length=500, upload_to='reports/artifacts/'),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
    ]
