# Generated by Django 5.0.6 on 2026-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_backfill_lowercase_report_definition_generator_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='output_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX'), ('PDF', 'PDF')], default='PDF', max_length=30),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(blank=True, choices=[('alert_summary', 'Alert Summary'), ('notification_delivery', 'Notification Delivery'), ('device_inventory', 'Device Inventory'), ('alert_export', 'Alert Export'), ('audit_export', 'Audit Export'), ('telemetry_export', 'Telemetry Export'), ('room_environment', 'Environmental Trends Report'), ('ups_performance', 'UPS Performance')], default='', max_length=100),
        ),
    ]
