# Generated by Django 5.0.6 on 2026-08-05 06:00

from django.db import migrations, models


ADD_ARTIFACT_COLUMNS_SQL = """
ALTER TABLE "report_artifacts"
    ADD COLUMN IF NOT EXISTS "artifact_type" varchar(30) NOT NULL DEFAULT 'PRIMARY',
    ADD COLUMN IF NOT EXISTS "file_name" varchar(255) NULL,
    ADD COLUMN IF NOT EXISTS "status" varchar(30) NOT NULL DEFAULT 'AVAILABLE',
    ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone NULL;
"""

BACKFILL_ARTIFACT_COLUMNS_SQL = """
UPDATE "report_artifacts"
SET
    "artifact_type" = COALESCE(NULLIF(BTRIM("artifact_type"), ''), 'PRIMARY'),
    "status" = COALESCE(NULLIF(BTRIM("status"), ''), 'AVAILABLE'),
    "file_name" = COALESCE(NULLIF(BTRIM("file_name"), ''), NULLIF(BTRIM(REGEXP_REPLACE(COALESCE("file", ''), '^.*/', '')), ''))
WHERE
    "artifact_type" IS NULL
    OR BTRIM("artifact_type") = ''
    OR "status" IS NULL
    OR BTRIM("status") = ''
    OR "file_name" IS NULL
    OR BTRIM("file_name") = '';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0021_alter_reportschedule_output_format_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ADD_ARTIFACT_COLUMNS_SQL, reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(BACKFILL_ARTIFACT_COLUMNS_SQL, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reportartifact",
                    name="artifact_type",
                    field=models.CharField(default="PRIMARY", max_length=30),
                ),
                migrations.AddField(
                    model_name="reportartifact",
                    name="file_name",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="reportartifact",
                    name="status",
                    field=models.CharField(default="AVAILABLE", max_length=30),
                ),
                migrations.AddField(
                    model_name="reportartifact",
                    name="expires_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
