# Generated by Django 5.0.6 on 2026-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0022_reportartifact_live_schema_alignment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="reportdelivery",
                    name="attempt_number",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="reportdelivery",
                    name="destination_snapshot",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="reportdelivery",
                    name="recipient_type",
                    field=models.CharField(blank=True, default="", max_length=30),
                ),
            ],
            database_operations=[],
        ),
    ]
