# Generated by Django 5.0.6 on 2026-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0023_reportdelivery_attempt_number_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="reportschedulerecipient",
                    name="recipient_type",
                    field=models.CharField(blank=True, default="", max_length=30),
                ),
                migrations.AddField(
                    model_name="reportschedulerecipient",
                    name="destination",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            database_operations=[],
        ),
    ]
