# Generated by Django 5.0.6 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0026_reconcile_recipient_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportschedule",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alert_summary", "Daily alert summary"),
                    ("notification_delivery", "Notification Delivery"),
                    ("device_inventory", "Device Inventory"),
                    ("alert_export", "Alert Export"),
                    ("audit_export", "Audit Export"),
                    ("telemetry_export", "Telemetry Export"),
                    ("room_environment", "Environmental Trends Report"),
                    ("ups_performance", "UPS Performance"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
