# Generated by Django 5.0.6 on 2026-06-28 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenters', '0001_initial'),
        ('devices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('POWER', 'Power'), ('ENERGY', 'Energy'), ('COOLING', 'Cooling'), ('ENVIRONMENT', 'Environment'), ('STATUS', 'Status'), ('ALARM', 'Alarm'), ('NETWORK', 'Network'), ('OTHER', 'Other')], max_length=50)),
                ('data_type', models.CharField(choices=[('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('TEXT', 'Text')], default='FLOAT', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'metric_definitions',
                'indexes': [models.Index(fields=['code'], name='metric_defi_code_074f1a_idx'), models.Index(fields=['category'], name='metric_defi_categor_c9c1ba_idx'), models.Index(fields=['is_active'], name='metric_defi_is_acti_aaa691_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryIngestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingest_id', models.UUIDField(db_index=True)),
                ('protocol', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_logs', to='devices.device')),
            ],
            options={
                'db_table': 'telemetry_ingest_logs',
            },
        ),
        migrations.CreateModel(
            name='TelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('STALE', 'Stale'), ('UNKNOWN', 'Unknown')], db_index=True, default='GOOD', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('ingest_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='datacenters.datacenter')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='devices.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_points', to='telemetry.metricdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='organizations.organization')),
            ],
            options={
                'db_table': 'telemetry_points',
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(max_length=150)),
                ('event_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='datacenters.datacenter')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'device_events',
                'indexes': [models.Index(fields=['organization', 'data_center'], name='device_even_organiz_b36f08_idx'), models.Index(fields=['device'], name='device_even_device__7978ab_idx'), models.Index(fields=['severity'], name='device_even_severit_09ac28_idx'), models.Index(fields=['occurred_at'], name='device_even_occurre_71779a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LatestTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('STALE', 'Stale'), ('UNKNOWN', 'Unknown')], default='GOOD', max_length=20)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_telemetry', to='datacenters.datacenter')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_telemetry', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_telemetry', to='organizations.organization')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_telemetry', to='telemetry.metricdefinition')),
            ],
            options={
                'db_table': 'latest_telemetry',
                'indexes': [models.Index(fields=['organization', 'data_center'], name='latest_tele_organiz_441575_idx'), models.Index(fields=['device', 'metric'], name='latest_tele_device__9226aa_idx'), models.Index(fields=['last_seen_at'], name='latest_tele_last_se_bff15a_idx'), models.Index(fields=['quality'], name='latest_tele_quality_9dfe26_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='latesttelemetry',
            constraint=models.UniqueConstraint(fields=('device', 'metric'), name='uq_latest_device_metric'),
        ),
        migrations.AddIndex(
            model_name='telemetryingestlog',
            index=models.Index(fields=['ingest_id'], name='telemetry_i_ingest__55467a_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryingestlog',
            index=models.Index(fields=['device'], name='telemetry_i_device__f8ba1e_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryingestlog',
            index=models.Index(fields=['protocol'], name='telemetry_i_protoco_5b6036_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryingestlog',
            index=models.Index(fields=['status'], name='telemetry_i_status_ed7125_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryingestlog',
            index=models.Index(fields=['started_at'], name='telemetry_i_started_c88fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['device', 'metric', 'time'], name='telemetry_p_device__5d1b53_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['data_center', 'time'], name='telemetry_p_data_ce_bdb319_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['organization', 'time'], name='telemetry_p_organiz_06f26f_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['metric', 'time'], name='telemetry_p_metric__c5646f_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['quality'], name='telemetry_p_quality_d2d3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['ingest_id'], name='telemetry_p_ingest__ade37f_idx'),
        ),
    ]
