# Generated by Django 5.0.6 on 2026-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesttelemetry',
            name='raw_value_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrypoint',
            name='raw_value_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
