# Generated by Codex on 2026-08-02

import uuid

from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_read_at_alter_notification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(blank=True, choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("WEB", "Web"), ("WEBHOOK", "Webhook")], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(blank=True, choices=[("PENDING", "Pending"), ("DELIVERING", "Delivering"), ("SENT", "Sent"), ("FAILED", "Failed")], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("EMAIL", "Email"), ("SMS", "SMS"), ("WEB", "Web"), ("WEBHOOK", "Webhook")], max_length=30)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("DELIVERING", "Delivering"), ("SENT", "Sent"), ("FAILED", "Failed")], db_index=True, default="PENDING", max_length=30)),
                ("recipient_address", models.CharField(blank=True, max_length=255, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("delivering_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notification_deliveries",
            },
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(fields=("notification", "channel"), name="unique_notification_delivery_channel"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["notification"], name="notif_deliv_notif_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["channel"], name="notif_deliv_chan_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status"], name="notif_deliv_status_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["next_retry_at"], name="notif_deliv_next_retry_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["created_at"], name="notif_deliv_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["sent_at"], name="notif_deliv_sent_at_idx"),
        ),
    ]
