# Generated by Codex on 2026-08-02

from collections import defaultdict

from django.db import migrations, transaction


def _logical_key(notification):
    metadata = notification.metadata if isinstance(notification.metadata, dict) else {}
    alert_event_id = metadata.get("alert_event_id") or metadata.get("alert_id")
    action = metadata.get("action")
    policy_id = metadata.get("policy_id")
    recipient_id = getattr(notification, "recipient_id", None)
    dedupe_key = notification.dedupe_key or ""

    if alert_event_id and action:
        if str(action).upper() == "ESCALATED" and policy_id:
            return f"alert:{alert_event_id}:ESCALATED:{policy_id}:{recipient_id}"
        return f"alert:{alert_event_id}:{action}:{recipient_id}"

    if dedupe_key.startswith("alert:"):
        parts = dedupe_key.split(":")
        if len(parts) == 5:
            return ":".join(parts[:3] + parts[4:])
        if len(parts) >= 6 and parts[2] == "ESCALATED":
            return ":".join(parts[:4] + parts[5:])

    return dedupe_key or f"notification:{notification.pk}"


def _logical_metadata(notification, logical_key):
    metadata = notification.metadata if isinstance(notification.metadata, dict) else {}
    logical_metadata = {
        "action": metadata.get("action"),
        "severity": metadata.get("severity"),
        "alert_event_id": metadata.get("alert_event_id") or metadata.get("alert_id"),
        "alert_status": metadata.get("alert_status"),
        "device_id": metadata.get("device_id"),
        "metric_id": metadata.get("metric_id"),
        "policy_id": metadata.get("policy_id"),
        "legacy_dedupe_key": notification.dedupe_key,
        "logical_dedupe_key": logical_key,
    }
    return {key: value for key, value in logical_metadata.items() if value is not None}


def _recipient_address(notification, channel):
    recipient = getattr(notification, "recipient", None)
    if channel == "EMAIL":
        return getattr(recipient, "email", None) if recipient else None
    if channel == "SMS":
        if not recipient:
            return None
        for field in ("phone", "mobile", "phone_number", "msisdn"):
            value = getattr(recipient, field, None)
            if value:
                return str(value).strip()
    return None


def _representative_row(rows):
    preferred_web = [row for row in rows if row.channel == "WEB"]
    if preferred_web:
        return sorted(preferred_web, key=lambda row: (row.created_at or row.updated_at, str(row.pk)))[0]
    return sorted(rows, key=lambda row: (row.created_at or row.updated_at, str(row.pk)))[0]


def forwards(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    NotificationDelivery = apps.get_model("notifications", "NotificationDelivery")

    legacy_rows = list(
        Notification.objects.filter(channel__isnull=False).select_related("recipient", "organization").order_by("created_at", "pk")
    )
    grouped = defaultdict(list)
    for row in legacy_rows:
        grouped[_logical_key(row)].append(row)

    for logical_key, rows in grouped.items():
        with transaction.atomic():
            source_rows = [
                {
                    "pk": row.pk,
                    "channel": row.channel,
                    "status": row.status,
                    "sent_at": row.sent_at,
                    "error_message": row.error_message,
                    "read_at": row.read_at,
                    "created_at": row.created_at,
                    "updated_at": row.updated_at,
                    "metadata": row.metadata if isinstance(row.metadata, dict) else {},
                    "recipient_id": row.recipient_id,
                    "recipient_email": getattr(row.recipient, "email", None) if getattr(row, "recipient", None) else None,
                    "recipient_phone": _recipient_address(row, row.channel),
                }
                for row in rows
            ]
            existing_logical = Notification.objects.filter(dedupe_key=logical_key, channel__isnull=True).order_by("created_at", "pk").first()
            representative = existing_logical or _representative_row(rows)

            if existing_logical is None:
                representative.channel = None
                representative.status = None
                representative.sent_at = None
                representative.error_message = None
                representative.dedupe_key = logical_key
                representative.metadata = _logical_metadata(representative, logical_key)

                web_rows = [row for row in source_rows if row["channel"] == "WEB"]
                if web_rows and any(row["read_at"] for row in web_rows):
                    representative.read_at = next((row["read_at"] for row in web_rows if row["read_at"]), None)
                elif not web_rows:
                    representative.read_at = next((row["read_at"] for row in sorted(source_rows, key=lambda row: (row["created_at"] or row["updated_at"], str(row["pk"]))) if row["read_at"]), None)
                representative.save(update_fields=["dedupe_key", "channel", "status", "sent_at", "error_message", "metadata", "read_at", "updated_at"])

            logical_notification = representative if existing_logical is None else existing_logical
            if existing_logical is not None and existing_logical.dedupe_key != logical_key:
                existing_logical.dedupe_key = logical_key
                existing_logical.metadata = _logical_metadata(existing_logical, logical_key)
                existing_logical.save(update_fields=["dedupe_key", "metadata", "updated_at"])

            earliest_created = min((row["created_at"] for row in source_rows if row["created_at"]), default=logical_notification.created_at)
            latest_updated = max((row["updated_at"] for row in source_rows if row["updated_at"]), default=logical_notification.updated_at)
            if earliest_created and logical_notification.created_at != earliest_created:
                Notification.objects.filter(pk=logical_notification.pk).update(created_at=earliest_created)
            if latest_updated and logical_notification.updated_at != latest_updated:
                Notification.objects.filter(pk=logical_notification.pk).update(updated_at=latest_updated)

            web_read_at = next((row["read_at"] for row in source_rows if row["channel"] == "WEB" and row["read_at"]), None)
            if web_read_at is None:
                non_null_reads = [row["read_at"] for row in source_rows if row["read_at"]]
                web_read_at = min(non_null_reads) if non_null_reads else None
            if web_read_at is not None:
                Notification.objects.filter(pk=logical_notification.pk).update(read_at=web_read_at)

            for row in source_rows:
                delivery_defaults = {
                    "status": row["status"] or "PENDING",
                    "recipient_address": row["recipient_phone"] or row["recipient_email"],
                    "attempt_count": 0,
                    "max_attempts": 3,
                    "queued_at": row["created_at"],
                    "delivering_at": row["updated_at"] if row["status"] == "DELIVERING" else None,
                    "sent_at": row["sent_at"],
                    "failed_at": row["updated_at"] if row["status"] == "FAILED" else None,
                    "next_retry_at": None,
                    "provider_message_id": None,
                    "provider_response": {},
                    "error_message": row["error_message"],
                    "metadata": row["metadata"],
                }
                NotificationDelivery.objects.update_or_create(
                    notification_id=logical_notification.pk,
                    channel=row["channel"],
                    defaults=delivery_defaults,
                )

            legacy_ids = [row["pk"] for row in source_rows if row["pk"] != logical_notification.pk or existing_logical is not None]
            Notification.objects.filter(pk__in=legacy_ids, channel__isnull=False).delete()


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationdelivery_and_notification_compat"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
