# Generated by Django 5.0.6 on 2026-08-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_migrate_legacy_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_notific_9901ae_idx',
            old_name='notif_deliv_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_channel_b52ae2_idx',
            old_name='notif_deliv_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_status_ab0dcc_idx',
            old_name='notif_deliv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_next_re_f74caa_idx',
            old_name='notif_deliv_next_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_created_fee8f7_idx',
            old_name='notif_deliv_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_sent_at_1c9053_idx',
            old_name='notif_deliv_sent_at_idx',
        ),
    ]
