# Generated by Django 5.0.6 on 2026-08-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_rename_notif_deliv_notif_idx_notificatio_notific_9901ae_idx_and_more"),
        ("reports", "0018_alter_reportartifact_file_alter_reportjob_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdelivery",
            name="report_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_deliveries",
                to="reports.reportdelivery",
            ),
        ),
    ]
